/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class com_imgvo_CUtils */

#ifndef _Included_com_imgvo_CUtils
#define _Included_com_imgvo_CUtils
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     com_imgvo_CUtils
 * Method:    name
 * Signature: ()Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_com_imgvo_CUtils_name
  (JNIEnv *, jclass);

JNIEXPORT void JNICALL Java_com_imgvo_MyConn_callJni
   (JNIEnv *, jobject);

#ifdef __cplusplus
}
#endif
#endif
