/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class com_a_ndklib_SVideo */

#ifndef _Included_com_a_ndklib_SVideo
#define _Included_com_a_ndklib_SVideo
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     com_a_ndklib_SVideo
 * Method:    title
 * Signature: ()Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_com_a_ndklib_SVideo_title
  (JNIEnv *, jclass);

#ifdef __cplusplus
}
#endif
#endif
